# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: false
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
    exception:
        enabled: true
        # codes:
        #     App\Exception\MyException: 403
    view:
        view_response_listener:  
          enabled: true
          force: true
        formats:
            json: true
